name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Passo 1: Checar o repositório
    - name: Checkout repository
      uses: actions/checkout@v4

    # Passo 2: Configurar o Node.js (Se for um projeto Node.js, por exemplo)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Você pode mudar para a versão que precisar

    # Passo 3: Instalar as dependências do projeto
    - name: Install dependencies
      run: npm install

    # Passo 4: Rodar os testes do projeto
    - name: Run tests
      run: npm test
    
    # Passo 5: Construir o projeto (se aplicável, no caso de front-end, build de produção)
    - name: Build project
      run: npm run build

  # Job para Docker (caso você tenha Dockerfile no seu projeto)
  dockerize:
    runs-on: ubuntu-latest
    needs: build  # Só executa após o job 'build'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Passo 1: Configuração do Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      # Passo 2: Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t my-image-name .
      
      # Passo 3: Rodar o container Docker
      - name: Run Docker container
        run: |
          docker run -d --name my-container my-image-name

  # Job para Deployment (caso você queira fazer o deploy)
  deploy:
    runs-on: ubuntu-latest
    needs: dockerize  # Só executa após o job 'dockerize'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 1: Configurar deploy (Exemplo de deploy para DigitalOcean, AWS ou outro servidor)
      - name: Deploy to server
        run: |
          ssh user@your-server "cd /path/to/your/project && git pull && npm install && npm run start"
        
      # Ou se estiver usando algum serviço de deploy automatizado, configure aqui.
